terms:
  - id: Aquatic and Atmospheric Sciences
    term: Aquatic and Atmospheric Sciences
  - id: Clinical Nutrition
    term: Clinical Nutrition
  - id: Economic Development
    term: Economic Development
  - id: Environmental Chemistry and Biology
    term: Environmental Chemistry and Biology
  - id: Environmental Engineering
    term: Environmental Engineering
  - id: Environmental Health Sciences
    term: Environmental Health Sciences
  - id: Environmental Management and Policy
    term: Environmental Management and Policy
  - id: Housing and Community Development
    term: Housing and Community Development
  - id: Industrial Hygiene
    term: Industrial Hygiene
  - id: Land Use and Environmental Planning
    term: Land Use and Environmental Planning
  - id: Public Health Nutrition
    term: Public Health Nutrition
  - id: Sustainable Water Resources
    term: Sustainable Water Resources
  - id: Transportation Planning
    term: Transportation Planning
  - id: Water Resources Engineering
    term: Water Resources Engineering


