terms:
  - id: http://rightsstatements.org/vocab/InC/1.0/
    term: "In Copyright"
    active: all
  - id: http://rightsstatements.org/vocab/InC-OW-EU/1.0/
    term: "In Copyright - EU Orphan Work"
    active: general
  - id: http://rightsstatements.org/vocab/InC-EDU/1.0/
    term: "In Copyright - Educational Use Permitted"
    active: general
  - id: http://rightsstatements.org/vocab/InC-NC/1.0/
    term: "In Copyright - Non-Commercial Use Permitted"
    active: general
  - id: http://rightsstatements.org/vocab/InC-RUU/1.0/
    term: "In Copyright - Rights-holder(s) Unlocatable or Unidentifiable"
    active: general
  - id: http://rightsstatements.org/vocab/NoC-CR/1.0/
    term: "No Copyright - Contractual Restrictions"
    active: general
  - id: http://rightsstatements.org/vocab/NoC-NC/1.0/
    term: "No Copyright - Non-Commercial Use Only "
    active: general
  - id: http://rightsstatements.org/vocab/NoC-OKLR/1.0/
    term: "No Copyright - Other Known Legal Restrictions"
    active: general
  - id: http://rightsstatements.org/vocab/NoC-US/1.0/
    term: "No Copyright - United States"
    active: all
  - id: http://rightsstatements.org/vocab/CNE/1.0/
    term: "Copyright Not Evaluated"
    active: general
  - id: http://rightsstatements.org/vocab/UND/1.0/
    term: "Copyright Undetermined"
    active: all
  - id: http://rightsstatements.org/vocab/NKC/1.0/
    term: "No Known Copyright"
    active: all
  - id: http://www.europeana.eu/portal/rights/rr-r.html
    term: "Old - Do Not Use"
    active: general